#!/bin/bash
if [ "$1" = "--version" ]; then
  echo "${TARGET}-gcc (GCC) 15.2 20250808 (release)"
  echo "Copyright (C) 2025 Free Software Foundation, Inc."
  echo "This is free software; see the source for copying conditions.  There is NO"
  echo "warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE."
else
  exec $thecc -Wno-unknown-warning-option "${@/-fno-var-tracking-assignments/}"
  # exec $thecc "$theargs"
fi